import { z } from "zod";

export const ProcessResourceSchema = z.object({
  memory: z.number(),
  cpu: z.number(),
});
export type ProcessResource = z.infer<typeof ProcessResourceSchema>;

export const StackFrameSchema = z.object({
  name: z.string(),
  filename: z.string(),
  module: z.string().nullable(),
  short_filename: z.string(),
  line: z.number(),
  locals: z.null(), // TODO: What is this
  is_entry: z.boolean(),
});
export type StackFrame = z.infer<typeof StackFrameSchema>;

export const ThreadDumpSchema = z.object({
  pid: z.number(),
  thread_id: z.number(),
  thread_name: z.string().nullable(),
  os_thread_id: z.number(),
  active: z.boolean(),
  owns_gil: z.boolean(),
  frames: z.array(StackFrameSchema),
  process_info: z.null(), // TODO: What is this?
});
export type ThreadDump = z.infer<typeof ThreadDumpSchema>;

export const ProcessReportEntrySchema = z.object({
  stacktraces: z.array(ThreadDumpSchema),
  resources: ProcessResourceSchema,
  index: z.number(),
  time: z.number(),
});
export type ProcessReportEntry = z.infer<typeof ProcessReportEntrySchema>;

export type ProcessId = string;
export type ProcessReport = {
  id: ProcessId;
  entries: ProcessReportEntry[];
};

export type CompleteReport = ProcessReport[];

export type PlotData = {
  reports: ProcessReport[];
  xData: number[];
  yData: (number | null)[][];
};

export function parseJsonProcessReport(
  id: ProcessId,
  reportString: string
): ProcessReport {
  const entries = [];

  for (const line of reportString.split("\n")) {
    if (!line) {
      continue;
    }
    entries.push(ProcessReportEntrySchema.parse(JSON.parse(line)));
  }

  return {
    id,
    entries,
  };
}

export function processReportToSeries(
  report: ProcessReport,
  xAxisTimes: number[]
): { cpuValues: (number | null)[]; memoryValues: (number | null)[] } {
  let memoryValues = [];
  let cpuValues = [];
  let currentTime = xAxisTimes[0];

  // Pad with nulls until our time has come
  while (currentTime < report.entries[0].time) {
    memoryValues.push(null);
    cpuValues.push(null);
  }
  // Copy over the entries
  for (const entry of report.entries) {
    memoryValues.push(entry.resources.memory);
    cpuValues.push(entry.resources.cpu);
  }
  // Fill the rest with nulls
  for (let i = cpuValues.length; i < xAxisTimes.length; i++) {
    cpuValues.push(null);
    memoryValues.push(null);
  }

  return {
    cpuValues,
    memoryValues,
  };
}

export function completeReportToSeries(reports: CompleteReport): PlotData {
  const seriesArray = [];
  const reportArray = [];
  const xAxisTimes = getxAxisTimes(reports);

  for (const report of reports) {
    reportArray.push(report);
    const series = processReportToSeries(report, xAxisTimes);
    seriesArray.push(series.cpuValues);
    seriesArray.push(series.memoryValues);
  }

  return {
    reports: reportArray,
    xData: xAxisTimes,
    yData: seriesArray,
  };
}

function getxAxisTimes(reports: CompleteReport) {
  const xAxisTimes = new Set<number>();

  for (const report of reports.values()) {
    for (const entry of report.entries) {
      xAxisTimes.add(entry.time);
    }
  }

  const asArray = Array.from(xAxisTimes);
  asArray.sort();

  return asArray;
}

function baseUrl(): string {
  if (window.location.port === "5173") {
    return "http://localhost:3000";
  }
  return "";
}

export async function fetchReportNames(): Promise<string[]> {
  const response = await fetch(`${baseUrl()}/view/profiles.json`);
  if (response.status !== 200) {
    console.log(response.status);
    alert("Error fetching server reports");
    console.log(await response.text);
  }
  return z.array(z.string()).parse(await response.json());
}

export async function fetchReportByName(name: string) {
  const response = await fetch(`${baseUrl()}/view/${name}`);
  if (response.status !== 200) {
    console.log(response.status);
    alert(`Error fetching report ${name}`);
    console.log(await response.text);
  }
  return parseJsonProcessReport(name, await response.text());
}

export const SAMPLE_REPORT = `{"stacktraces":[{"pid":1500937,"thread_id":138677306980160,"thread_name":"MainThread","os_thread_id":1500937,"active":true,"owns_gil":true,"frames":[{"name":"random_elements","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/providers/__init__.py","module":null,"short_filename":"faker/providers/__init__.py","line":492,"locals":null,"is_entry":false},{"name":"random_element","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/providers/__init__.py","module":null,"short_filename":"faker/providers/__init__.py","line":552,"locals":null,"is_entry":false},{"name":"first_name_male","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/providers/person/__init__.py","module":null,"short_filename":"faker/providers/person/__init__.py","line":240,"locals":null,"is_entry":false},{"name":"format","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/generator.py","module":null,"short_filename":"faker/generator.py","line":88,"locals":null,"is_entry":false},{"name":"__format_token","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/generator.py","module":null,"short_filename":"faker/generator.py","line":189,"locals":null,"is_entry":false},{"name":"parse","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/generator.py","module":null,"short_filename":"faker/generator.py","line":175,"locals":null,"is_entry":false},{"name":"name","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/providers/person/__init__.py","module":null,"short_filename":"faker/providers/person/__init__.py","line":206,"locals":null,"is_entry":false},{"name":"generate_data","filename":"/home/i_al_istannen/src/python/py-crude-resource-monitor/examples/polars-example.py","module":null,"short_filename":"polars-example.py","line":15,"locals":null,"is_entry":false},{"name":"<module>","filename":"/home/i_al_istannen/src/python/py-crude-resource-monitor/examples/polars-example.py","module":null,"short_filename":"polars-example.py","line":29,"locals":null,"is_entry":false}],"process_info":null}],"resources":{"memory":51740672,"cpu":0.0,"cpu_global":19.53872},"index":0,"time":1732966901720}
{"stacktraces":[{"pid":1500937,"thread_id":138677306980160,"thread_name":"MainThread","os_thread_id":1500937,"active":true,"owns_gil":true,"frames":[{"name":"__format_token","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/generator.py","module":null,"short_filename":"faker/generator.py","line":191,"locals":null,"is_entry":false},{"name":"parse","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/generator.py","module":null,"short_filename":"faker/generator.py","line":175,"locals":null,"is_entry":false},{"name":"name","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/providers/person/__init__.py","module":null,"short_filename":"faker/providers/person/__init__.py","line":206,"locals":null,"is_entry":false},{"name":"generate_data","filename":"/home/i_al_istannen/src/python/py-crude-resource-monitor/examples/polars-example.py","module":null,"short_filename":"polars-example.py","line":15,"locals":null,"is_entry":false},{"name":"<module>","filename":"/home/i_al_istannen/src/python/py-crude-resource-monitor/examples/polars-example.py","module":null,"short_filename":"polars-example.py","line":29,"locals":null,"is_entry":false}],"process_info":null}],"resources":{"memory":53444608,"cpu":86.4,"cpu_global":28.9},"index":1,"time":1732966902801}
{"stacktraces":[{"pid":1500937,"thread_id":138677306980160,"thread_name":"MainThread","os_thread_id":1500937,"active":true,"owns_gil":true,"frames":[{"name":"__format_token","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/generator.py","module":null,"short_filename":"faker/generator.py","line":191,"locals":null,"is_entry":false},{"name":"parse","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/generator.py","module":null,"short_filename":"faker/generator.py","line":175,"locals":null,"is_entry":false},{"name":"name","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/providers/person/__init__.py","module":null,"short_filename":"faker/providers/person/__init__.py","line":206,"locals":null,"is_entry":false},{"name":"generate_data","filename":"/home/i_al_istannen/src/python/py-crude-resource-monitor/examples/polars-example.py","module":null,"short_filename":"polars-example.py","line":15,"locals":null,"is_entry":false},{"name":"<module>","filename":"/home/i_al_istannen/src/python/py-crude-resource-monitor/examples/polars-example.py","module":null,"short_filename":"polars-example.py","line":29,"locals":null,"is_entry":false}],"process_info":null}],"resources":{"memory":54099968,"cpu":102.34742,"cpu_global":47.887325},"index":2,"time":1732966903917}
{"stacktraces":[{"pid":1500937,"thread_id":138677306980160,"thread_name":"MainThread","os_thread_id":1500937,"active":true,"owns_gil":true,"frames":[{"name":"choices_distribution","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/utils/distribution.py","module":null,"short_filename":"faker/utils/distribution.py","line":73,"locals":null,"is_entry":false},{"name":"random_elements","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/providers/__init__.py","module":null,"short_filename":"faker/providers/__init__.py","line":500,"locals":null,"is_entry":false},{"name":"random_element","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/providers/__init__.py","module":null,"short_filename":"faker/providers/__init__.py","line":552,"locals":null,"is_entry":false},{"name":"last_name","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/providers/person/__init__.py","module":null,"short_filename":"faker/providers/person/__init__.py","line":212,"locals":null,"is_entry":false},{"name":"format","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/generator.py","module":null,"short_filename":"faker/generator.py","line":88,"locals":null,"is_entry":false},{"name":"__format_token","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/generator.py","module":null,"short_filename":"faker/generator.py","line":189,"locals":null,"is_entry":false},{"name":"parse","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/generator.py","module":null,"short_filename":"faker/generator.py","line":175,"locals":null,"is_entry":false},{"name":"name","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/providers/person/__init__.py","module":null,"short_filename":"faker/providers/person/__init__.py","line":206,"locals":null,"is_entry":false},{"name":"generate_data","filename":"/home/i_al_istannen/src/python/py-crude-resource-monitor/examples/polars-example.py","module":null,"short_filename":"polars-example.py","line":15,"locals":null,"is_entry":false},{"name":"<module>","filename":"/home/i_al_istannen/src/python/py-crude-resource-monitor/examples/polars-example.py","module":null,"short_filename":"polars-example.py","line":29,"locals":null,"is_entry":false}],"process_info":null}],"resources":{"memory":54755328,"cpu":96.24724,"cpu_global":48.896248},"index":3,"time":1732966905008}
{"stacktraces":[{"pid":1500937,"thread_id":138677306980160,"thread_name":"MainThread","os_thread_id":1500937,"active":true,"owns_gil":true,"frames":[{"name":"date_time_ad","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/providers/date_time/__init__.py","module":null,"short_filename":"faker/providers/date_time/__init__.py","line":1896,"locals":null,"is_entry":false},{"name":"date_of_birth","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/providers/date_time/__init__.py","module":null,"short_filename":"faker/providers/date_time/__init__.py","line":2502,"locals":null,"is_entry":false},{"name":"generate_data","filename":"/home/i_al_istannen/src/python/py-crude-resource-monitor/examples/polars-example.py","module":null,"short_filename":"polars-example.py","line":16,"locals":null,"is_entry":false},{"name":"<module>","filename":"/home/i_al_istannen/src/python/py-crude-resource-monitor/examples/polars-example.py","module":null,"short_filename":"polars-example.py","line":29,"locals":null,"is_entry":false}],"process_info":null}],"resources":{"memory":55017472,"cpu":103.464195,"cpu_global":54.387993},"index":4,"time":1732966906261}
{"stacktraces":[{"pid":1500937,"thread_id":138677306980160,"thread_name":"MainThread","os_thread_id":1500937,"active":true,"owns_gil":true,"frames":[{"name":"random_elements","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/providers/__init__.py","module":null,"short_filename":"faker/providers/__init__.py","line":492,"locals":null,"is_entry":false},{"name":"random_element","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/providers/__init__.py","module":null,"short_filename":"faker/providers/__init__.py","line":552,"locals":null,"is_entry":false},{"name":"last_name","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/providers/person/__init__.py","module":null,"short_filename":"faker/providers/person/__init__.py","line":212,"locals":null,"is_entry":false},{"name":"format","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/generator.py","module":null,"short_filename":"faker/generator.py","line":88,"locals":null,"is_entry":false},{"name":"__format_token","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/generator.py","module":null,"short_filename":"faker/generator.py","line":189,"locals":null,"is_entry":false},{"name":"parse","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/generator.py","module":null,"short_filename":"faker/generator.py","line":175,"locals":null,"is_entry":false},{"name":"name","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/providers/person/__init__.py","module":null,"short_filename":"faker/providers/person/__init__.py","line":206,"locals":null,"is_entry":false},{"name":"generate_data","filename":"/home/i_al_istannen/src/python/py-crude-resource-monitor/examples/polars-example.py","module":null,"short_filename":"polars-example.py","line":15,"locals":null,"is_entry":false},{"name":"<module>","filename":"/home/i_al_istannen/src/python/py-crude-resource-monitor/examples/polars-example.py","module":null,"short_filename":"polars-example.py","line":29,"locals":null,"is_entry":false}],"process_info":null}],"resources":{"memory":56983552,"cpu":87.5502,"cpu_global":43.07229},"index":5,"time":1732966907388}
{"stacktraces":[{"pid":1500937,"thread_id":138677306980160,"thread_name":"MainThread","os_thread_id":1500937,"active":true,"owns_gil":true,"frames":[{"name":"generate_data","filename":"/home/i_al_istannen/src/python/py-crude-resource-monitor/examples/polars-example.py","module":null,"short_filename":"polars-example.py","line":18,"locals":null,"is_entry":false},{"name":"<module>","filename":"/home/i_al_istannen/src/python/py-crude-resource-monitor/examples/polars-example.py","module":null,"short_filename":"polars-example.py","line":29,"locals":null,"is_entry":false}],"process_info":null}],"resources":{"memory":57769984,"cpu":96.80968,"cpu_global":48.29483},"index":6,"time":1732966908506}
{"stacktraces":[{"pid":1500937,"thread_id":138677306980160,"thread_name":"MainThread","os_thread_id":1500937,"active":true,"owns_gil":true,"frames":[{"name":"random_elements","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/providers/__init__.py","module":null,"short_filename":"faker/providers/__init__.py","line":492,"locals":null,"is_entry":false},{"name":"random_element","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/providers/__init__.py","module":null,"short_filename":"faker/providers/__init__.py","line":552,"locals":null,"is_entry":false},{"name":"first_name_male","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/providers/person/__init__.py","module":null,"short_filename":"faker/providers/person/__init__.py","line":240,"locals":null,"is_entry":false},{"name":"format","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/generator.py","module":null,"short_filename":"faker/generator.py","line":88,"locals":null,"is_entry":false},{"name":"__format_token","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/generator.py","module":null,"short_filename":"faker/generator.py","line":189,"locals":null,"is_entry":false},{"name":"parse","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/generator.py","module":null,"short_filename":"faker/generator.py","line":175,"locals":null,"is_entry":false},{"name":"name","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/providers/person/__init__.py","module":null,"short_filename":"faker/providers/person/__init__.py","line":206,"locals":null,"is_entry":false},{"name":"generate_data","filename":"/home/i_al_istannen/src/python/py-crude-resource-monitor/examples/polars-example.py","module":null,"short_filename":"polars-example.py","line":15,"locals":null,"is_entry":false},{"name":"<module>","filename":"/home/i_al_istannen/src/python/py-crude-resource-monitor/examples/polars-example.py","module":null,"short_filename":"polars-example.py","line":29,"locals":null,"is_entry":false}],"process_info":null}],"resources":{"memory":58556416,"cpu":102.088165,"cpu_global":47.563805},"index":7,"time":1732966909628}
{"stacktraces":[{"pid":1500937,"thread_id":138677306980160,"thread_name":"MainThread","os_thread_id":1500937,"active":true,"owns_gil":true,"frames":[{"name":"random_elements","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/providers/__init__.py","module":null,"short_filename":"faker/providers/__init__.py","line":492,"locals":null,"is_entry":false},{"name":"random_element","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/providers/__init__.py","module":null,"short_filename":"faker/providers/__init__.py","line":552,"locals":null,"is_entry":false},{"name":"last_name","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/providers/person/__init__.py","module":null,"short_filename":"faker/providers/person/__init__.py","line":212,"locals":null,"is_entry":false},{"name":"format","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/generator.py","module":null,"short_filename":"faker/generator.py","line":88,"locals":null,"is_entry":false},{"name":"__format_token","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/generator.py","module":null,"short_filename":"faker/generator.py","line":189,"locals":null,"is_entry":false},{"name":"parse","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/generator.py","module":null,"short_filename":"faker/generator.py","line":175,"locals":null,"is_entry":false},{"name":"name","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/providers/person/__init__.py","module":null,"short_filename":"faker/providers/person/__init__.py","line":206,"locals":null,"is_entry":false},{"name":"generate_data","filename":"/home/i_al_istannen/src/python/py-crude-resource-monitor/examples/polars-example.py","module":null,"short_filename":"polars-example.py","line":15,"locals":null,"is_entry":false},{"name":"<module>","filename":"/home/i_al_istannen/src/python/py-crude-resource-monitor/examples/polars-example.py","module":null,"short_filename":"polars-example.py","line":29,"locals":null,"is_entry":false}],"process_info":null}],"resources":{"memory":58949632,"cpu":98.07037,"cpu_global":59.023838},"index":8,"time":1732966910757}
{"stacktraces":[{"pid":1500937,"thread_id":138677306980160,"thread_name":"MainThread","os_thread_id":1500937,"active":true,"owns_gil":true,"frames":[{"name":"random_elements","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/providers/__init__.py","module":null,"short_filename":"faker/providers/__init__.py","line":492,"locals":null,"is_entry":false},{"name":"random_element","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/providers/__init__.py","module":null,"short_filename":"faker/providers/__init__.py","line":552,"locals":null,"is_entry":false},{"name":"last_name","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/providers/person/__init__.py","module":null,"short_filename":"faker/providers/person/__init__.py","line":212,"locals":null,"is_entry":false},{"name":"format","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/generator.py","module":null,"short_filename":"faker/generator.py","line":88,"locals":null,"is_entry":false},{"name":"__format_token","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/generator.py","module":null,"short_filename":"faker/generator.py","line":189,"locals":null,"is_entry":false},{"name":"parse","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/generator.py","module":null,"short_filename":"faker/generator.py","line":175,"locals":null,"is_entry":false},{"name":"name","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/providers/person/__init__.py","module":null,"short_filename":"faker/providers/person/__init__.py","line":206,"locals":null,"is_entry":false},{"name":"generate_data","filename":"/home/i_al_istannen/src/python/py-crude-resource-monitor/examples/polars-example.py","module":null,"short_filename":"polars-example.py","line":15,"locals":null,"is_entry":false},{"name":"<module>","filename":"/home/i_al_istannen/src/python/py-crude-resource-monitor/examples/polars-example.py","module":null,"short_filename":"polars-example.py","line":29,"locals":null,"is_entry":false}],"process_info":null}],"resources":{"memory":59473920,"cpu":97.77778,"cpu_global":53.444447},"index":9,"time":1732966911855}
{"stacktraces":[{"pid":1500937,"thread_id":138677306980160,"thread_name":"MainThread","os_thread_id":1500937,"active":true,"owns_gil":true,"frames":[{"name":"choices","filename":"/nix/store/04gg5w1s662l329a8kh9xcwyp0k64v5a-python3-3.12.4/lib/python3.12/random.py","module":null,"short_filename":"random.py","line":469,"locals":null,"is_entry":false},{"name":"choices_distribution","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/utils/distribution.py","module":null,"short_filename":"faker/utils/distribution.py","line":73,"locals":null,"is_entry":false},{"name":"random_elements","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/providers/__init__.py","module":null,"short_filename":"faker/providers/__init__.py","line":500,"locals":null,"is_entry":false},{"name":"random_element","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/providers/__init__.py","module":null,"short_filename":"faker/providers/__init__.py","line":552,"locals":null,"is_entry":false},{"name":"last_name","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/providers/person/__init__.py","module":null,"short_filename":"faker/providers/person/__init__.py","line":212,"locals":null,"is_entry":false},{"name":"format","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/generator.py","module":null,"short_filename":"faker/generator.py","line":88,"locals":null,"is_entry":false},{"name":"__format_token","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/generator.py","module":null,"short_filename":"faker/generator.py","line":189,"locals":null,"is_entry":false},{"name":"parse","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/generator.py","module":null,"short_filename":"faker/generator.py","line":175,"locals":null,"is_entry":false},{"name":"name","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/providers/person/__init__.py","module":null,"short_filename":"faker/providers/person/__init__.py","line":206,"locals":null,"is_entry":false},{"name":"generate_data","filename":"/home/i_al_istannen/src/python/py-crude-resource-monitor/examples/polars-example.py","module":null,"short_filename":"polars-example.py","line":15,"locals":null,"is_entry":false},{"name":"<module>","filename":"/home/i_al_istannen/src/python/py-crude-resource-monitor/examples/polars-example.py","module":null,"short_filename":"polars-example.py","line":29,"locals":null,"is_entry":false}],"process_info":null}],"resources":{"memory":60784640,"cpu":100.22778,"cpu_global":44.19134},"index":10,"time":1732966912954}
{"stacktraces":[{"pid":1500937,"thread_id":138677306980160,"thread_name":"MainThread","os_thread_id":1500937,"active":true,"owns_gil":true,"frames":[{"name":"choices_distribution","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/utils/distribution.py","module":null,"short_filename":"faker/utils/distribution.py","line":73,"locals":null,"is_entry":false},{"name":"random_elements","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/providers/__init__.py","module":null,"short_filename":"faker/providers/__init__.py","line":500,"locals":null,"is_entry":false},{"name":"random_element","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/providers/__init__.py","module":null,"short_filename":"faker/providers/__init__.py","line":552,"locals":null,"is_entry":false},{"name":"last_name","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/providers/person/__init__.py","module":null,"short_filename":"faker/providers/person/__init__.py","line":212,"locals":null,"is_entry":false},{"name":"format","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/generator.py","module":null,"short_filename":"faker/generator.py","line":88,"locals":null,"is_entry":false},{"name":"__format_token","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/generator.py","module":null,"short_filename":"faker/generator.py","line":189,"locals":null,"is_entry":false},{"name":"parse","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/generator.py","module":null,"short_filename":"faker/generator.py","line":175,"locals":null,"is_entry":false},{"name":"name","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/providers/person/__init__.py","module":null,"short_filename":"faker/providers/person/__init__.py","line":206,"locals":null,"is_entry":false},{"name":"generate_data","filename":"/home/i_al_istannen/src/python/py-crude-resource-monitor/examples/polars-example.py","module":null,"short_filename":"polars-example.py","line":15,"locals":null,"is_entry":false},{"name":"<module>","filename":"/home/i_al_istannen/src/python/py-crude-resource-monitor/examples/polars-example.py","module":null,"short_filename":"polars-example.py","line":29,"locals":null,"is_entry":false}],"process_info":null}],"resources":{"memory":61571072,"cpu":99.65398,"cpu_global":37.94694},"index":11,"time":1732966914036}
{"stacktraces":[{"pid":1500937,"thread_id":138677306980160,"thread_name":"MainThread","os_thread_id":1500937,"active":true,"owns_gil":true,"frames":[{"name":"random_elements","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/providers/__init__.py","module":null,"short_filename":"faker/providers/__init__.py","line":492,"locals":null,"is_entry":false},{"name":"random_element","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/providers/__init__.py","module":null,"short_filename":"faker/providers/__init__.py","line":552,"locals":null,"is_entry":false},{"name":"first_name_male","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/providers/person/__init__.py","module":null,"short_filename":"faker/providers/person/__init__.py","line":240,"locals":null,"is_entry":false},{"name":"format","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/generator.py","module":null,"short_filename":"faker/generator.py","line":88,"locals":null,"is_entry":false},{"name":"__format_token","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/generator.py","module":null,"short_filename":"faker/generator.py","line":189,"locals":null,"is_entry":false},{"name":"parse","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/generator.py","module":null,"short_filename":"faker/generator.py","line":175,"locals":null,"is_entry":false},{"name":"name","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/providers/person/__init__.py","module":null,"short_filename":"faker/providers/person/__init__.py","line":206,"locals":null,"is_entry":false},{"name":"generate_data","filename":"/home/i_al_istannen/src/python/py-crude-resource-monitor/examples/polars-example.py","module":null,"short_filename":"polars-example.py","line":15,"locals":null,"is_entry":false},{"name":"<module>","filename":"/home/i_al_istannen/src/python/py-crude-resource-monitor/examples/polars-example.py","module":null,"short_filename":"polars-example.py","line":29,"locals":null,"is_entry":false}],"process_info":null}],"resources":{"memory":62619648,"cpu":106.98225,"cpu_global":54.08284},"index":12,"time":1732966915220}
{"stacktraces":[{"pid":1500937,"thread_id":138677306980160,"thread_name":"MainThread","os_thread_id":1500937,"active":true,"owns_gil":true,"frames":[{"name":"choices","filename":"/nix/store/04gg5w1s662l329a8kh9xcwyp0k64v5a-python3-3.12.4/lib/python3.12/random.py","module":null,"short_filename":"random.py","line":488,"locals":null,"is_entry":false},{"name":"choices_distribution","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/utils/distribution.py","module":null,"short_filename":"faker/utils/distribution.py","line":73,"locals":null,"is_entry":false},{"name":"random_elements","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/providers/__init__.py","module":null,"short_filename":"faker/providers/__init__.py","line":500,"locals":null,"is_entry":false},{"name":"random_element","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/providers/__init__.py","module":null,"short_filename":"faker/providers/__init__.py","line":552,"locals":null,"is_entry":false},{"name":"first_name_male","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/providers/person/__init__.py","module":null,"short_filename":"faker/providers/person/__init__.py","line":240,"locals":null,"is_entry":false},{"name":"format","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/generator.py","module":null,"short_filename":"faker/generator.py","line":88,"locals":null,"is_entry":false},{"name":"__format_token","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/generator.py","module":null,"short_filename":"faker/generator.py","line":189,"locals":null,"is_entry":false},{"name":"parse","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/generator.py","module":null,"short_filename":"faker/generator.py","line":175,"locals":null,"is_entry":false},{"name":"name","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/providers/person/__init__.py","module":null,"short_filename":"faker/providers/person/__init__.py","line":206,"locals":null,"is_entry":false},{"name":"generate_data","filename":"/home/i_al_istannen/src/python/py-crude-resource-monitor/examples/polars-example.py","module":null,"short_filename":"polars-example.py","line":15,"locals":null,"is_entry":false},{"name":"<module>","filename":"/home/i_al_istannen/src/python/py-crude-resource-monitor/examples/polars-example.py","module":null,"short_filename":"polars-example.py","line":29,"locals":null,"is_entry":false}],"process_info":null}],"resources":{"memory":63143936,"cpu":92.05021,"cpu_global":64.53975},"index":13,"time":1732966916333}
{"stacktraces":[{"pid":1500937,"thread_id":138677306980160,"thread_name":"MainThread","os_thread_id":1500937,"active":true,"owns_gil":true,"frames":[{"name":"random_elements","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/providers/__init__.py","module":null,"short_filename":"faker/providers/__init__.py","line":492,"locals":null,"is_entry":false},{"name":"random_element","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/providers/__init__.py","module":null,"short_filename":"faker/providers/__init__.py","line":552,"locals":null,"is_entry":false},{"name":"last_name","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/providers/person/__init__.py","module":null,"short_filename":"faker/providers/person/__init__.py","line":212,"locals":null,"is_entry":false},{"name":"format","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/generator.py","module":null,"short_filename":"faker/generator.py","line":88,"locals":null,"is_entry":false},{"name":"__format_token","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/generator.py","module":null,"short_filename":"faker/generator.py","line":189,"locals":null,"is_entry":false},{"name":"parse","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/generator.py","module":null,"short_filename":"faker/generator.py","line":175,"locals":null,"is_entry":false},{"name":"name","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/providers/person/__init__.py","module":null,"short_filename":"faker/providers/person/__init__.py","line":206,"locals":null,"is_entry":false},{"name":"generate_data","filename":"/home/i_al_istannen/src/python/py-crude-resource-monitor/examples/polars-example.py","module":null,"short_filename":"polars-example.py","line":15,"locals":null,"is_entry":false},{"name":"<module>","filename":"/home/i_al_istannen/src/python/py-crude-resource-monitor/examples/polars-example.py","module":null,"short_filename":"polars-example.py","line":29,"locals":null,"is_entry":false}],"process_info":null}],"resources":{"memory":63799296,"cpu":100.801834,"cpu_global":44.100803},"index":14,"time":1732966917445}
{"stacktraces":[{"pid":1500937,"thread_id":138677306980160,"thread_name":"MainThread","os_thread_id":1500937,"active":true,"owns_gil":true,"frames":[{"name":"choices","filename":"/nix/store/04gg5w1s662l329a8kh9xcwyp0k64v5a-python3-3.12.4/lib/python3.12/random.py","module":null,"short_filename":"random.py","line":469,"locals":null,"is_entry":false},{"name":"choices_distribution","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/utils/distribution.py","module":null,"short_filename":"faker/utils/distribution.py","line":73,"locals":null,"is_entry":false},{"name":"random_elements","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/providers/__init__.py","module":null,"short_filename":"faker/providers/__init__.py","line":500,"locals":null,"is_entry":false},{"name":"random_element","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/providers/__init__.py","module":null,"short_filename":"faker/providers/__init__.py","line":552,"locals":null,"is_entry":false},{"name":"last_name","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/providers/person/__init__.py","module":null,"short_filename":"faker/providers/person/__init__.py","line":212,"locals":null,"is_entry":false},{"name":"format","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/generator.py","module":null,"short_filename":"faker/generator.py","line":88,"locals":null,"is_entry":false},{"name":"__format_token","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/generator.py","module":null,"short_filename":"faker/generator.py","line":189,"locals":null,"is_entry":false},{"name":"parse","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/generator.py","module":null,"short_filename":"faker/generator.py","line":175,"locals":null,"is_entry":false},{"name":"name","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/providers/person/__init__.py","module":null,"short_filename":"faker/providers/person/__init__.py","line":206,"locals":null,"is_entry":false},{"name":"generate_data","filename":"/home/i_al_istannen/src/python/py-crude-resource-monitor/examples/polars-example.py","module":null,"short_filename":"polars-example.py","line":15,"locals":null,"is_entry":false},{"name":"<module>","filename":"/home/i_al_istannen/src/python/py-crude-resource-monitor/examples/polars-example.py","module":null,"short_filename":"polars-example.py","line":29,"locals":null,"is_entry":false}],"process_info":null}],"resources":{"memory":65110016,"cpu":98.97844,"cpu_global":45.85698},"index":15,"time":1732966918542}
{"stacktraces":[{"pid":1500937,"thread_id":138677306980160,"thread_name":"MainThread","os_thread_id":1500937,"active":true,"owns_gil":true,"frames":[{"name":"choices","filename":"/nix/store/04gg5w1s662l329a8kh9xcwyp0k64v5a-python3-3.12.4/lib/python3.12/random.py","module":null,"short_filename":"random.py","line":469,"locals":null,"is_entry":false},{"name":"choices_distribution","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/utils/distribution.py","module":null,"short_filename":"faker/utils/distribution.py","line":73,"locals":null,"is_entry":false},{"name":"random_elements","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/providers/__init__.py","module":null,"short_filename":"faker/providers/__init__.py","line":500,"locals":null,"is_entry":false},{"name":"random_element","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/providers/__init__.py","module":null,"short_filename":"faker/providers/__init__.py","line":552,"locals":null,"is_entry":false},{"name":"last_name","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/providers/person/__init__.py","module":null,"short_filename":"faker/providers/person/__init__.py","line":212,"locals":null,"is_entry":false},{"name":"format","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/generator.py","module":null,"short_filename":"faker/generator.py","line":88,"locals":null,"is_entry":false},{"name":"__format_token","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/generator.py","module":null,"short_filename":"faker/generator.py","line":189,"locals":null,"is_entry":false},{"name":"parse","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/generator.py","module":null,"short_filename":"faker/generator.py","line":175,"locals":null,"is_entry":false},{"name":"name","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/providers/person/__init__.py","module":null,"short_filename":"faker/providers/person/__init__.py","line":206,"locals":null,"is_entry":false},{"name":"generate_data","filename":"/home/i_al_istannen/src/python/py-crude-resource-monitor/examples/polars-example.py","module":null,"short_filename":"polars-example.py","line":15,"locals":null,"is_entry":false},{"name":"<module>","filename":"/home/i_al_istannen/src/python/py-crude-resource-monitor/examples/polars-example.py","module":null,"short_filename":"polars-example.py","line":29,"locals":null,"is_entry":false}],"process_info":null}],"resources":{"memory":65896448,"cpu":100.11376,"cpu_global":37.883957},"index":16,"time":1732966919675}
{"stacktraces":[{"pid":1500937,"thread_id":138677306980160,"thread_name":"MainThread","os_thread_id":1500937,"active":true,"owns_gil":true,"frames":[{"name":"random_elements","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/providers/__init__.py","module":null,"short_filename":"faker/providers/__init__.py","line":492,"locals":null,"is_entry":false},{"name":"random_element","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/providers/__init__.py","module":null,"short_filename":"faker/providers/__init__.py","line":552,"locals":null,"is_entry":false},{"name":"last_name","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/providers/person/__init__.py","module":null,"short_filename":"faker/providers/person/__init__.py","line":212,"locals":null,"is_entry":false},{"name":"format","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/generator.py","module":null,"short_filename":"faker/generator.py","line":88,"locals":null,"is_entry":false},{"name":"__format_token","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/generator.py","module":null,"short_filename":"faker/generator.py","line":189,"locals":null,"is_entry":false},{"name":"parse","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/generator.py","module":null,"short_filename":"faker/generator.py","line":175,"locals":null,"is_entry":false},{"name":"name","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/providers/person/__init__.py","module":null,"short_filename":"faker/providers/person/__init__.py","line":206,"locals":null,"is_entry":false},{"name":"generate_data","filename":"/home/i_al_istannen/src/python/py-crude-resource-monitor/examples/polars-example.py","module":null,"short_filename":"polars-example.py","line":15,"locals":null,"is_entry":false},{"name":"<module>","filename":"/home/i_al_istannen/src/python/py-crude-resource-monitor/examples/polars-example.py","module":null,"short_filename":"polars-example.py","line":29,"locals":null,"is_entry":false}],"process_info":null}],"resources":{"memory":66551808,"cpu":96.28008,"cpu_global":50.437634},"index":17,"time":1732966920780}
{"stacktraces":[{"pid":1500937,"thread_id":138677306980160,"thread_name":"MainThread","os_thread_id":1500937,"active":true,"owns_gil":true,"frames":[{"name":"choices","filename":"/nix/store/04gg5w1s662l329a8kh9xcwyp0k64v5a-python3-3.12.4/lib/python3.12/random.py","module":null,"short_filename":"random.py","line":469,"locals":null,"is_entry":false},{"name":"choices_distribution","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/utils/distribution.py","module":null,"short_filename":"faker/utils/distribution.py","line":73,"locals":null,"is_entry":false},{"name":"random_elements","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/providers/__init__.py","module":null,"short_filename":"faker/providers/__init__.py","line":500,"locals":null,"is_entry":false},{"name":"random_element","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/providers/__init__.py","module":null,"short_filename":"faker/providers/__init__.py","line":552,"locals":null,"is_entry":false},{"name":"first_name_female","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/providers/person/__init__.py","module":null,"short_filename":"faker/providers/person/__init__.py","line":250,"locals":null,"is_entry":false},{"name":"format","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/generator.py","module":null,"short_filename":"faker/generator.py","line":88,"locals":null,"is_entry":false},{"name":"__format_token","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/generator.py","module":null,"short_filename":"faker/generator.py","line":189,"locals":null,"is_entry":false},{"name":"parse","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/generator.py","module":null,"short_filename":"faker/generator.py","line":175,"locals":null,"is_entry":false},{"name":"name","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/providers/person/__init__.py","module":null,"short_filename":"faker/providers/person/__init__.py","line":206,"locals":null,"is_entry":false},{"name":"generate_data","filename":"/home/i_al_istannen/src/python/py-crude-resource-monitor/examples/polars-example.py","module":null,"short_filename":"polars-example.py","line":15,"locals":null,"is_entry":false},{"name":"<module>","filename":"/home/i_al_istannen/src/python/py-crude-resource-monitor/examples/polars-example.py","module":null,"short_filename":"polars-example.py","line":29,"locals":null,"is_entry":false}],"process_info":null}],"resources":{"memory":67076096,"cpu":102.304146,"cpu_global":69.58525},"index":18,"time":1732966921948}
{"stacktraces":[{"pid":1500937,"thread_id":138677306980160,"thread_name":"MainThread","os_thread_id":1500937,"active":true,"owns_gil":true,"frames":[{"name":"choices_distribution","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/utils/distribution.py","module":null,"short_filename":"faker/utils/distribution.py","line":73,"locals":null,"is_entry":false},{"name":"random_elements","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/providers/__init__.py","module":null,"short_filename":"faker/providers/__init__.py","line":500,"locals":null,"is_entry":false},{"name":"random_element","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/providers/__init__.py","module":null,"short_filename":"faker/providers/__init__.py","line":552,"locals":null,"is_entry":false},{"name":"last_name","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/providers/person/__init__.py","module":null,"short_filename":"faker/providers/person/__init__.py","line":212,"locals":null,"is_entry":false},{"name":"format","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/generator.py","module":null,"short_filename":"faker/generator.py","line":88,"locals":null,"is_entry":false},{"name":"__format_token","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/generator.py","module":null,"short_filename":"faker/generator.py","line":189,"locals":null,"is_entry":false},{"name":"parse","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/generator.py","module":null,"short_filename":"faker/generator.py","line":175,"locals":null,"is_entry":false},{"name":"name","filename":"/nix/store/wxc13l8mxgz6hnfq87anm9i9v0r0ascd-python3.12-faker-25.8.0/lib/python3.12/site-packages/faker/providers/person/__init__.py","module":null,"short_filename":"faker/providers/person/__init__.py","line":206,"locals":null,"is_entry":false},{"name":"generate_data","filename":"/home/i_al_istannen/src/python/py-crude-resource-monitor/examples/polars-example.py","module":null,"short_filename":"polars-example.py","line":15,"locals":null,"is_entry":false},{"name":"<module>","filename":"/home/i_al_istannen/src/python/py-crude-resource-monitor/examples/polars-example.py","module":null,"short_filename":"polars-example.py","line":29,"locals":null,"is_entry":false}],"process_info":null}],"resources":{"memory":67600384,"cpu":94.168465,"cpu_global":68.89848},"index":19,"time":1732966923065}
{"stacktraces":[{"pid":1500937,"thread_id":138677306980160,"thread_name":"MainThread","os_thread_id":1500937,"active":true,"owns_gil":true,"frames":[{"name":"generate_data","filename":"/home/i_al_istannen/src/python/py-crude-resource-monitor/examples/polars-example.py","module":null,"short_filename":"polars-example.py","line":24,"locals":null,"is_entry":false},{"name":"<module>","filename":"/home/i_al_istannen/src/python/py-crude-resource-monitor/examples/polars-example.py","module":null,"short_filename":"polars-example.py","line":29,"locals":null,"is_entry":false}],"process_info":null}],"resources":{"memory":68255744,"cpu":96.567,"cpu_global":61.794018},"index":20,"time":1732966924165}
{"stacktraces":[{"pid":1500937,"thread_id":138677306980160,"thread_name":"MainThread","os_thread_id":1500937,"active":true,"owns_gil":true,"frames":[{"name":"<module>","filename":"/home/i_al_istannen/src/python/py-crude-resource-monitor/examples/polars-example.py","module":null,"short_filename":"polars-example.py","line":29,"locals":null,"is_entry":false}],"process_info":null}],"resources":{"memory":161103872,"cpu":100.801834,"cpu_global":51.890034},"index":21,"time":1732966925272}
`;
